Add SoilAndPeatland categories and SiteType categories
menu-hanke/forest-data-model pull request #21
Opened 2022-06-06 07:37 UTC by unie31

2022-06-06 07:42 UTC, unie31 commented on forestdatamodel/conversion/internal2mela.py
> +            raise TypeError
With this I tried to capture the bug found in the earlier implementation where soil_peatland_category was determined wrongly when site_Type_category was not set. However I have a feeling that raising may not be the ideal solution so I'm open to improvement suggestions.

2022-06-06 09:08 UTC, jpy-luke commented on forestdatamodel/conversion/internal2mela.py
> +            raise TypeError
Rather return None

2022-06-06 09:12 UTC, jpy-luke commented on forestdatamodel/enums/internal.py
> +    UNSPECIFIED_TREELESS_MIRE = 6 # VMI "avosuo"
Didn't we agree that just TREELESS_MIRE is enough? Specifying barren or rich is done via the SiteType specifically upon a need for it, like with Mela conversion.

2022-06-06 09:13 UTC, jpy-luke requested changes
See line comments

2022-06-07 05:39 UTC, jpy-luke commented on forestdatamodel/conversion/internal2mela.py
>          if target.site_type_category in __mela_rich_mire_types:
No need for early return. Early returns generally make code more difficult to understand with multiple exit points from functions. Make the second if an `elif`. This allows us to trust at a glance that the if-else construct of this function always does only one thing.

2022-06-07 05:40 UTC, jpy-luke requested changes
Another comment to resolve

2022-06-08 06:02 UTC, merged